Fix CI python version & add private maps

diff --git a/.github/workflows/release-engine.yml b/.github/workflows/release-engine.yml
--- a/.github/workflows/release-engine.yml
+++ b/.github/workflows/release-engine.yml
@@ -25,6 +25,10 @@ jobs:
       id-token: write
 
     steps:
+      - uses: conda-incubator/setup-miniconda@v3
+        with:
+          python-version: 3.12
+
       - name: Checkout branch
         uses: actions/checkout@v3
 
@@ -45,31 +49,31 @@ jobs:
       - name: Set up Google Cloud SDK
         uses: 'google-github-actions/setup-gcloud@v1'
 
-      # TODO: private maps
-      #- name: Clone private maps
-      #  if: ${{ env.IS_PUBLIC != 'YES' }}
-      #  uses: actions/checkout@v3
-      #  with:
-      #    repository: battlecode/private-maps
-      #    token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
-      #    path: private-maps
-      #
-      #- name: Inject private maps
-      #  if: ${{ env.IS_PUBLIC != 'YES' }}
-      #  run: |
-      #    source="private-maps/$RELEASE_ARTIFACT_ID"
-      #    dest="engine/src/main/battlecode/world/resources"
-      #    if [ -d "$source" ]; then
-      #      cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
-      #      if [ -s "private-maps-copy-log" ]; then
-      #        echo "FAILED! Public and private maps should not intersect."
-      #        cat private-maps-copy-log
-      #        exit 1
-      #      fi
-      #    fi
+      - name: Clone private maps
+        if: ${{ env.IS_PUBLIC != 'YES' }}
+        uses: actions/checkout@v3
+        with:
+          repository: battlecode/private-maps
+          token: ${{ secrets.CI_REPOSITORY_CLONE_PAT }}
+          path: private-maps
+      
+      - name: Inject private maps
+        if: ${{ env.IS_PUBLIC != 'YES' }}
+        run: |
+          source="private-maps/$RELEASE_ARTIFACT_ID"
+          dest="battlecode25/maps"
+          if [ -d "$source" ]; then
+            cp -r -i "$source/." "$dest/" < /dev/null &> private-maps-copy-log
+            if [ -s "private-maps-copy-log" ]; then
+              echo "FAILED! Public and private maps should not intersect."
+              cat private-maps-copy-log
+              exit 1
+            fi
+          fi
           
       - name: Build python package 
         run: |
+          python --version # Print python version
           pip install --upgrade build
           SETUPTOOLS_SCM_PRETEND_VERSION=${RELEASE_VERSION} python -m build
 
